openapi: 3.0.0
info:
  version: '1.0'
  title: REST API
  contact:
    name: Владимир
    email: vladimir.ylmv@gmail.com
servers:
  - url: 'https://example.com/v1.0'
    description: Live Server
tags:
  - name: Раздел
    description: |
      API для портала КиноПоиск
security:
  - SecretApiKey: []
  - JWT: []
paths:
  /top:
    $ref: ./paths/top.yaml
  /getepisode/{id}:
    $ref: ./paths/episode.yaml
  /getfilm/{id}:
    $ref: ./paths/film.yaml
  /addmark/{id}:
    $ref: ./paths/addmark.yaml
  /addepisode/{id}:
      $ref: ./paths/addepisode.yaml
  /auth:
    $ref: ./paths/auth.yaml
  /register:
    $ref: ./paths/createuser.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT